curl -X POST -d "questions[0][type]=control_head" 
-d "questions[0][text]=Contact Form Zonguldak" 
-d "questions[0][order]=1" 
-d "questions[0][name]=Header" 
-d "questions[1][type]=control_fullname" 
-d "questions[1][text]=Full Name" 
-d "questions[1][order]=2" 
-d "questions[1][name]=TextBox" 
-d "questions[1][validation]=None" 
-d "questions[1][required]=Yes" 
-d "questions[1][readonly]=No" 
-d "questions[1][size]=20" 
-d "questions[1][labelAlign]=Left" 
-d "questions[1][hint]= "
-d "questions[2][type]=control_phone" 
-d "questions[2][text]=Phone Number" 
-d "questions[2][order]=3" 
-d "questions[2][name]=TextBox" 
-d "questions[2][validation]=None" 
-d "questions[2][required]=Yes" 
-d "questions[2][readonly]=No" 
-d "questions[2][size]=20" 
-d "questions[2][labelAlign]=Left" 
-d "questions[2][hint]= "
-d "questions[3][type]=control_email" 
-d "questions[3][text]=Email" 
-d "questions[3][order]=4" 
-d "questions[3][name]=TextBox" 
-d "questions[3][validation]=None" 
-d "questions[3][required]=Yes" 
-d "questions[3][readonly]=No" 
-d "questions[3][size]=20" 
-d "questions[3][labelAlign]=Left" 
-d "questions[3][hint]= "
-d "questions[4][type]=control_textarea" 
-d "questions[4][text]=Notes" 
-d "questions[4][order]=5" 
-d "questions[4][name]=TextBox" 
-d "questions[4][validation]=None" 
-d "questions[4][required]=No" 
-d "questions[4][readonly]=No" 
-d "questions[4][size]=20" 
-d "questions[4][labelAlign]=Left" 
-d "questions[4][hint]= "
-d "questions[5][type]=control_button"
-d "questions[5][text]=Submit" 
-d "questions[5][order]=6" 
-d "properties[title]=Task-5 Zonguldak" 
-d "properties[height]=600" 
-d "emails[0][type]=autorespond" 
-d "emails[0][name]=notification" 
-d "emails[0][from]=noreply@jotform.com" 
-d "emails[0][to]=barispinara@gmail.com" 
-d "emails[0][subject]=Contact Form" 
-d "emails[0][html]=false" "https://api.jotform.com/form?apiKey={API KEY}"
    